name: Tests

on:
	push: 
    branches: [ dev ]
		branches: [ main ]

jobs:
	test_server:
		name: hello-world
		container: epitechcontent/epitest-docker
		runs-on: ubuntu-20-04

		steps:
    - name: checkout
      uses: actions/checkout@v2
		- name: Say hello world
			uses: echo "Welcome to the Github Actions workshop !"