## NAME OF THE WORKFLOW
name: workflow-name

## CONDITIONS FOR THE WORKFLOW TO RUN:
on:
  push:
    branches-ignore:
      - 'ga-ignore*'
  pull_request:
    branches-ignore:
      - 'ga-ignore*'

  workflow_dispatch:

## DEFAULTS FOR THE WORKFLOW:
defaults:
  run:
    shell: bash

jobs:
  initialize:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 3
    steps:
      - name: date
        run: date
      - name: checkout
        use: actions/checkout@v3
      - name: branch
        run: echo ${GITHUB_REF##*/}
      - name: size
        run: du -skh --exclude=".git"

  build:
    runs-on: ubuntu-latest
    ## TIMEOUT IN MINUTES (may change depending of the language like cpp):
    if: ${{ always() }}
    needs: initialize
    timeout-minutes: 3
    steps:
      - name: compile
        run: make

  ## FUNCTIONNAL TESTS
  functionnal_test:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [ initialize, build ]
    steps:
      - name: functionnal_test
        run: ./tests/functional-test.sh > result_bash_tests ; cat result_bash_tests
      - name: Artifact functionnal
        uses: actions/upload-artifact@v3
        with:
          name: result_bash_tests
          path: ./result_bash_tests

  ## UNITS TESTS
  unit_test:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [ initialize, build ]
    steps:
      - name: unit test
        run: make tests_run > result_unit_tests ; cat result_unit_tests
      - name: Artifact unit
        uses: actions/upload-artifact@v3
        with:
          name: result_unit_tests
          path: ./result_unit_tests
