name: my_sokoban

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_server:
    name: test_sokoban
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: compile
      run: make
    - name: test_bash
      run: ./tests/test_my_sokoban.sh