name: Tests

on:
  push: 
    branches:
    - main
    - master
    - dev
  pull_request: 
    branches:
    - main
    - master
    - dev
  
  workflow_dispatch:

jobs:
  test_server:
    name: hello-world
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop !"
    
  test_second:
    name: unit-test
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: unit-test
      run: make tests_run
    - name: coverage
      run: make coverage
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact create
        run: echo placeholder > tests/unit_test.txt 
        path: tests/unit_test.txt

  test_third:
    name: functionnal-test
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: functional-test
      run: ./tests/functional-test.sh
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact create
        run: echo placeholder > tests/functional_test.txt 
        path: tests/functional_test.txt 