name: Tests

on:
  push: 
    branches: [main, master, dev]
  pull_request: 
    branches: [main, master, dev]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test_server:
    name: hello-world
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Say hello world
      run: echo "Welcome to the Github Actions workshop !"
    
  test_second:
    name: unit-test
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: unit-test
      run: make tests_run > result_unit_test ; cat result_unit_test
    - name: coverage
      run: make coverage > result_coverage ; cat result_coverage
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: result_unit_test
        path: ./result_unit_test
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: result_coverage
        path: ./result_coverage

  test_third:
    name: functionnal-test
    container: epitechcontent/epitest-docker
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: compile
      run: make
    - name: functional-test
      run: ./functional-test.sh > result_functional_test ; cat result_functional_test
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: result_functiona_ltest
        path: ./result_functiona_ltest 
